### ISSUE TITLE
How to run this application in windows with docker?

### ISSUE THREAD

**Issue by saqib-ahmed** [mrhaki/grails-docker-sample#1]
I want to run this application in windows. I know I'll have to tweak the bash script for batch file syntax. what are other changes that need to be done. And how to change the bash file. Currently I'm getting this error when I execute `.\gradlew tasks`:

## Error Log:
``` bash
15:12:30.957 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.ResolvedConfigurationDependencyGraphVisitor] Attaching docker.app:grails-docker-sample:1.0(ag
ent) to its parents.
15:12:30.988 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.ResolvedConfigurationDependencyGraphVisitor] Attaching org.springframework:springloaded:1.2.4
.RELEASE(default) to its parents.
15:12:31.019 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.oldresult.TransientConfigurationResultsBuilder] Flushing resolved configuration data in Binary stor
e in C:\Users\saqib ahmad\AppData\Local\Temp\gradle8580267932820537196.bin. Wrote root docker.app:grails-docker-sample:1.0:agent.
15:12:31.057 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'springloaded.jar (org.springframework:springloaded:1
.2.4.RELEASE)' in resolver cache: C:\Users\saqib ahmad\.gradle\caches\modules-2\files-2.1\org.springframework\springloaded\1.2.4.RELEASE\903fb9c6a6a93326dc4e89731d584faebd6bd435\sp
ringloaded-1.2.4.RELEASE.jar
15:12:31.157 [ERROR] [org.gradle.BuildExceptionReporter]
15:12:31.172 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:12:31.172 [ERROR] [org.gradle.BuildExceptionReporter]
15:12:31.188 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
15:12:31.204 [ERROR] [org.gradle.BuildExceptionReporter] Script 'F:\Dev\grails-docker-sample\gradle\docker.gradle' line: 126
15:12:31.204 [ERROR] [org.gradle.BuildExceptionReporter]
15:12:31.235 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:12:31.235 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating script.
15:12:31.279 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find method defaultDependencies() for arguments [com.bmuschko.gradle.docker.DockerRemoteApiPlugin$_configureAbs
tractDockerTask_closure1_closure3@6b25ef1c] on configuration ':dockerJava'.
15:12:31.307 [ERROR] [org.gradle.BuildExceptionReporter]
15:12:31.330 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
15:12:31.339 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
15:12:31.368 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:12:31.392 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:12:31.400 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:12:31.424 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 39.604 secs
15:12:31.433 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (C:\Users\saqib ahmad\.gradle\caches\modules-2\metadata-
2.14\artifact-at-repository.bin)
15:12:31.455 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (C:\Users\saqib ahmad\.gradle\caches\modules-2\metadata-2.14\mo
dule-metadata.bin)

```
## Stack Trace:
```bash
* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating script.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:154)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:102)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:62)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
        at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_ac6wh1dn1rwxpqsifleynr3ua.run(F:\Dev\grails-docker-sample\build.gradle:82)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:154)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:492)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method defaultDependencies() for arguments [com.bmuschko.gradle.docker.DockerRemoteApiPlugin$_configureAbs
tractDockerTask_closure1_closure3@4e4395c] on configuration ':dockerJava'.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.invokeMethod(Unknown Source)
        at com.bmuschko.gradle.docker.DockerRemoteApiPlugin$_configureAbstractDockerTask_closure1.doCall(DockerRemoteApiPlugin.groovy:54)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:110)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:488)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:58)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
        at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:201)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:164)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:71)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:65)
        at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:867)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:225)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:129)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at docker_aogop911f64gf6ws67k0k3rcp.run(F:\Dev\grails-docker-sample\gradle\docker.gradle:126)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
        ... 46 more

```
I simply cloned the repository and executed the command.
Regards

**Comment by saqib-ahmed** [comment]
Never mind. Got it working on Linux. This seems to be a dead repo.
